INSERT INTO animal (id_character, type, wisdom) VALUES (1000, 'Чайка', 72);
INSERT INTO animal (id_character, type, wisdom) VALUES (1001, 'Крикет', 87);
INSERT INTO animal (id_character, type, wisdom) VALUES (1002, 'Саранча', 50);
INSERT INTO animal (id_character, type, wisdom) VALUES (1003, 'Пума', 81);
INSERT INTO animal (id_character, type, wisdom) VALUES (1004, 'Альбатрос', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1005, 'Кролик', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1006, 'Тукан', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1007, 'Дракон Комодо', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1008, 'Грызун', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1009, 'Стрекоза', 86);
INSERT INTO animal (id_character, type, wisdom) VALUES (1010, 'Сцинк', 77);
INSERT INTO animal (id_character, type, wisdom) VALUES (1011, 'Кит-пилот', 22);
INSERT INTO animal (id_character, type, wisdom) VALUES (1012, 'Хамелеон', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1013, 'Медуза Ируканджи', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1014, 'Гремучая змея', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1015, 'Комар', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1016, 'Муравейник', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1017, 'Лимпет', 46);
INSERT INTO animal (id_character, type, wisdom) VALUES (1018, 'Краб', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1019, 'Морской слон', 84);
INSERT INTO animal (id_character, type, wisdom) VALUES (1020, 'Муравьед', 2);
INSERT INTO animal (id_character, type, wisdom) VALUES (1021, 'Муравей', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1022, 'Скумбрия', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1023, 'Ежик', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1024, 'Кои', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1025, 'Жерех', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1026, 'Сапсан', 51);
INSERT INTO animal (id_character, type, wisdom) VALUES (1027, 'Примас', 34);
INSERT INTO animal (id_character, type, wisdom) VALUES (1028, 'Саламандра', 55);
INSERT INTO animal (id_character, type, wisdom) VALUES (1029, 'Тля', 18);
INSERT INTO animal (id_character, type, wisdom) VALUES (1030, 'Кошка', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1031, 'Крупный рогатый скот', 91);
INSERT INTO animal (id_character, type, wisdom) VALUES (1032, 'Буйвол', 16);
INSERT INTO animal (id_character, type, wisdom) VALUES (1033, 'Осьминог', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1034, 'Окунь', 16);
INSERT INTO animal (id_character, type, wisdom) VALUES (1035, 'Моль', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1036, 'Викунья', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1037, 'Скумбрия', 46);
INSERT INTO animal (id_character, type, wisdom) VALUES (1038, 'Джунглевая птица', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1039, 'Волк', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1040, 'Утка', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1041, 'Тиранозавр', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1042, 'Карибу', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1043, 'Дрозд', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1044, 'Кит', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1045, 'Опоссум', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1046, 'Тигр', 52);
INSERT INTO animal (id_character, type, wisdom) VALUES (1047, 'Крупный рогатый скот', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1048, 'Оса', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1049, 'Норка', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1050, 'Сахарный планер', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1051, 'Шелкопряд', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1052, 'Кролик', 81);
INSERT INTO animal (id_character, type, wisdom) VALUES (1053, 'заяц', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1054, 'Сцинк', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1055, 'Лемминг', 46);
INSERT INTO animal (id_character, type, wisdom) VALUES (1056, 'Цикада', 34);
INSERT INTO animal (id_character, type, wisdom) VALUES (1057, 'Газель', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1058, 'Черепаха', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1059, 'Морской конек', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1060, 'Красная панда', 87);
INSERT INTO animal (id_character, type, wisdom) VALUES (1061, 'Крапивник', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1062, 'Гиббон', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1063, 'Креветки', 82);
INSERT INTO animal (id_character, type, wisdom) VALUES (1064, 'Черепаха', 2);
INSERT INTO animal (id_character, type, wisdom) VALUES (1065, 'Монитор ящерицы', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1066, 'Древесная лягушка', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1067, 'Попугай', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1068, 'Гусь', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1069, 'Лемминг', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1070, 'Страус', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1071, 'Бонобо', 91);
INSERT INTO animal (id_character, type, wisdom) VALUES (1072, 'Сиг', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1073, 'Курица', 56);
INSERT INTO animal (id_character, type, wisdom) VALUES (1074, 'список', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1075, 'Морской слон', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1076, 'Земляной ленивец', 61);
INSERT INTO animal (id_character, type, wisdom) VALUES (1077, 'Курица', 18);
INSERT INTO animal (id_character, type, wisdom) VALUES (1078, 'Кальмар', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1079, 'Бегемот', 54);
INSERT INTO animal (id_character, type, wisdom) VALUES (1080, 'горный козел', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1081, 'Норка', 2);
INSERT INTO animal (id_character, type, wisdom) VALUES (1082, 'Гуппи', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1083, 'Голубь', 7);
INSERT INTO animal (id_character, type, wisdom) VALUES (1084, 'Вомбат', 47);
INSERT INTO animal (id_character, type, wisdom) VALUES (1085, 'Тиглон', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1086, 'Крачка', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1087, 'Курица', 81);
INSERT INTO animal (id_character, type, wisdom) VALUES (1088, 'Общество зяблик', 37);
INSERT INTO animal (id_character, type, wisdom) VALUES (1089, 'Жерех', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1090, 'Ластоногие', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1091, 'Лягушка', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1092, 'Газель', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1093, 'Песчанка', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1094, 'Наземная улитка', 56);
INSERT INTO animal (id_character, type, wisdom) VALUES (1095, 'Крот-звездочка', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1096, 'Землеройка', 51);
INSERT INTO animal (id_character, type, wisdom) VALUES (1097, 'Свинья', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1098, 'Горностай', 48);
INSERT INTO animal (id_character, type, wisdom) VALUES (1099, 'сельдь', 55);
INSERT INTO animal (id_character, type, wisdom) VALUES (1100, 'Зимородок', 90);
INSERT INTO animal (id_character, type, wisdom) VALUES (1101, 'список', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1102, 'Сорока', 55);
INSERT INTO animal (id_character, type, wisdom) VALUES (1103, 'Зебра зяблик', 61);
INSERT INTO animal (id_character, type, wisdom) VALUES (1104, 'Черепаха', 45);
INSERT INTO animal (id_character, type, wisdom) VALUES (1105, 'Божья коровка', 84);
INSERT INTO animal (id_character, type, wisdom) VALUES (1106, 'Галлиформный', 55);
INSERT INTO animal (id_character, type, wisdom) VALUES (1107, 'Овца', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1108, 'Саламандра', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1109, 'Рысь', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1110, 'Зяблик', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1111, 'Колибри', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1112, 'Гуппи', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1113, 'Гагара', 45);
INSERT INTO animal (id_character, type, wisdom) VALUES (1114, 'Коробка мармеладок', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1115, 'Моль', 84);
INSERT INTO animal (id_character, type, wisdom) VALUES (1116, 'Корова', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1117, 'Голубая сойка', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1118, 'Сова', 63);
INSERT INTO animal (id_character, type, wisdom) VALUES (1119, 'Свинья', 70);
INSERT INTO animal (id_character, type, wisdom) VALUES (1120, 'Рыба-ангел', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1121, 'Сумчатый', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1122, 'Осел', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1123, 'Богомол', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1124, 'Тукан', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1125, 'Курица', 84);
INSERT INTO animal (id_character, type, wisdom) VALUES (1126, 'Сокол', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1127, 'Навозный жук', 51);
INSERT INTO animal (id_character, type, wisdom) VALUES (1128, 'Хамелеон', 97);
INSERT INTO animal (id_character, type, wisdom) VALUES (1129, 'Тигр', 85);
INSERT INTO animal (id_character, type, wisdom) VALUES (1130, 'Росомаха', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1131, 'Мартышка', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1132, 'Колибри', 11);
INSERT INTO animal (id_character, type, wisdom) VALUES (1133, 'Певчая птица', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1134, 'Ласточка', 46);
INSERT INTO animal (id_character, type, wisdom) VALUES (1135, 'Медуза Ируканджи', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1136, 'Колпица', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1137, 'Пересмешник', 77);
INSERT INTO animal (id_character, type, wisdom) VALUES (1138, 'Чайка', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1139, 'Гиббон', 3);
INSERT INTO animal (id_character, type, wisdom) VALUES (1140, 'Собака', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1141, 'Соня', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1142, 'лось', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1143, 'Сурикат', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1144, 'Оса', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1145, 'Колпица', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1146, 'Суслик', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1147, 'Водяной удав', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1148, 'Утконос', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1149, 'Медуза', 48);
INSERT INTO animal (id_character, type, wisdom) VALUES (1150, 'Крупный рогатый скот', 63);
INSERT INTO animal (id_character, type, wisdom) VALUES (1151, 'Зебра', 83);
INSERT INTO animal (id_character, type, wisdom) VALUES (1152, 'Краб-стрела', 91);
INSERT INTO animal (id_character, type, wisdom) VALUES (1153, 'Курица', 58);
INSERT INTO animal (id_character, type, wisdom) VALUES (1154, 'Сом', 23);
INSERT INTO animal (id_character, type, wisdom) VALUES (1155, 'Волк', 82);
INSERT INTO animal (id_character, type, wisdom) VALUES (1156, 'горный козел', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1157, 'Горностай', 63);
INSERT INTO animal (id_character, type, wisdom) VALUES (1158, 'Млекопитающее', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1159, 'Ежик', 48);
INSERT INTO animal (id_character, type, wisdom) VALUES (1160, 'Гигантский кальмар', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1161, 'Оцелот', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1162, 'Дождевой червь', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1163, 'Буйвол', 72);
INSERT INTO animal (id_character, type, wisdom) VALUES (1164, 'Хорек', 86);
INSERT INTO animal (id_character, type, wisdom) VALUES (1165, 'Летучая мышь', 39);
INSERT INTO animal (id_character, type, wisdom) VALUES (1166, 'Тарантул', 33);
INSERT INTO animal (id_character, type, wisdom) VALUES (1167, 'Белка', 84);
INSERT INTO animal (id_character, type, wisdom) VALUES (1168, 'Гриф', 33);
INSERT INTO animal (id_character, type, wisdom) VALUES (1169, 'Головоногие моллюски', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1170, 'Лягушка', 63);
INSERT INTO animal (id_character, type, wisdom) VALUES (1171, 'Волк', 11);
INSERT INTO animal (id_character, type, wisdom) VALUES (1172, 'Карибу', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1173, 'Лемур', 33);
INSERT INTO animal (id_character, type, wisdom) VALUES (1174, 'Северный олень', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1175, 'Моль', 86);
INSERT INTO animal (id_character, type, wisdom) VALUES (1176, 'Парусник', 48);
INSERT INTO animal (id_character, type, wisdom) VALUES (1177, 'Обезьяна', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1178, 'морская свинка', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1179, 'Фруктовая летучая мышь', 93);
INSERT INTO animal (id_character, type, wisdom) VALUES (1180, 'Сиамские бойцовые рыбы', 10);
INSERT INTO animal (id_character, type, wisdom) VALUES (1181, 'Медведь гризли', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1182, 'Петух', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1183, 'Уриал', 81);
INSERT INTO animal (id_character, type, wisdom) VALUES (1184, 'Осетр', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1185, 'Пони', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1186, 'Португальский человек войны', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1187, 'Рыба-пила', 9);
INSERT INTO animal (id_character, type, wisdom) VALUES (1188, 'Василиск', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1189, 'Червь', 7);
INSERT INTO animal (id_character, type, wisdom) VALUES (1190, 'Гуань', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1191, 'Ара', 3);
INSERT INTO animal (id_character, type, wisdom) VALUES (1192, 'Летучая рыба', 37);
INSERT INTO animal (id_character, type, wisdom) VALUES (1193, 'сельдь', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1194, 'Хорек', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1195, 'Наземная улитка', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1196, 'Овца', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1197, 'Кошка', 36);
INSERT INTO animal (id_character, type, wisdom) VALUES (1198, 'Тукан', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1199, 'Гриф', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1200, 'морская свинка', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1201, 'Постельный клоп', 85);
INSERT INTO animal (id_character, type, wisdom) VALUES (1202, 'Дракон', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1203, 'Гусь', 84);
INSERT INTO animal (id_character, type, wisdom) VALUES (1204, 'Буйвол', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1205, 'Жаба', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1206, 'Рябчик', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1207, 'Планарий', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1208, 'Медуза', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1209, 'Луговая собачка', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1210, 'Куропатка', 52);
INSERT INTO animal (id_character, type, wisdom) VALUES (1211, 'Красная панда', 73);
INSERT INTO animal (id_character, type, wisdom) VALUES (1212, 'Пиранья', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1213, 'Опоссум', 51);
INSERT INTO animal (id_character, type, wisdom) VALUES (1214, 'Медуза', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1215, 'Викунья', 60);
INSERT INTO animal (id_character, type, wisdom) VALUES (1216, 'Жерех', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1217, 'Дикая кошка', 0);
INSERT INTO animal (id_character, type, wisdom) VALUES (1218, 'Хорек', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1219, 'Угорь', 82);
INSERT INTO animal (id_character, type, wisdom) VALUES (1220, 'Леопард', 56);
INSERT INTO animal (id_character, type, wisdom) VALUES (1221, 'Марлин', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1222, 'Ракушка', 27);
INSERT INTO animal (id_character, type, wisdom) VALUES (1223, 'Лягушка', 37);
INSERT INTO animal (id_character, type, wisdom) VALUES (1224, 'Колибри', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1225, 'Кошка', 75);
INSERT INTO animal (id_character, type, wisdom) VALUES (1226, 'список', 69);
INSERT INTO animal (id_character, type, wisdom) VALUES (1227, 'Обезьяна паук', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1228, 'Пересмешник', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1229, 'Гагара', 15);
INSERT INTO animal (id_character, type, wisdom) VALUES (1230, 'Носорог', 41);
INSERT INTO animal (id_character, type, wisdom) VALUES (1231, 'Синий кит', 18);
INSERT INTO animal (id_character, type, wisdom) VALUES (1232, 'Кит', 50);
INSERT INTO animal (id_character, type, wisdom) VALUES (1233, 'Сурок', 83);
INSERT INTO animal (id_character, type, wisdom) VALUES (1234, 'Сурикат', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1235, 'Скат манта', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1236, 'Кит', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1237, 'Куропатка', 51);
INSERT INTO animal (id_character, type, wisdom) VALUES (1238, 'Лебедь', 35);
INSERT INTO animal (id_character, type, wisdom) VALUES (1239, 'Хамелеон', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1240, 'заяц', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1241, 'Свинья', 16);
INSERT INTO animal (id_character, type, wisdom) VALUES (1242, 'Рак', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1243, 'рыба-меч', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1244, 'Барсук', 61);
INSERT INTO animal (id_character, type, wisdom) VALUES (1245, 'Козел', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1246, 'Удильщик', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1247, 'Треска', 82);
INSERT INTO animal (id_character, type, wisdom) VALUES (1248, 'Фазан', 45);
INSERT INTO animal (id_character, type, wisdom) VALUES (1249, 'Пчела', 19);
INSERT INTO animal (id_character, type, wisdom) VALUES (1250, 'Куница', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1251, 'Крикет', 15);
INSERT INTO animal (id_character, type, wisdom) VALUES (1252, 'Морской лев', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1253, 'Тапир', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1254, 'Павлин', 23);
INSERT INTO animal (id_character, type, wisdom) VALUES (1255, 'Английский указатель', 85);
INSERT INTO animal (id_character, type, wisdom) VALUES (1256, 'Гепард', 7);
INSERT INTO animal (id_character, type, wisdom) VALUES (1257, 'Куропатка', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1258, 'Панда', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1259, 'Грызун', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1260, 'Фруктовая летучая мышь', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1261, 'Кукушка', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1262, 'Корова', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1263, 'Моллюск', 72);
INSERT INTO animal (id_character, type, wisdom) VALUES (1264, 'Сумчатый', 55);
INSERT INTO animal (id_character, type, wisdom) VALUES (1265, 'Треска', 39);
INSERT INTO animal (id_character, type, wisdom) VALUES (1266, 'Арктическая лиса', 6);
INSERT INTO animal (id_character, type, wisdom) VALUES (1267, 'Ламантин', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1268, 'Лень', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1269, 'Гусь', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1270, 'Крупный рогатый скот', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1271, 'Буйвол', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1272, 'Паук-люк', 60);
INSERT INTO animal (id_character, type, wisdom) VALUES (1273, 'Капибара', 70);
INSERT INTO animal (id_character, type, wisdom) VALUES (1274, 'Наземная улитка', 90);
INSERT INTO animal (id_character, type, wisdom) VALUES (1275, 'Гигантский кальмар', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1276, 'Черная пантера', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1277, 'Гаял', 70);
INSERT INTO animal (id_character, type, wisdom) VALUES (1278, 'Тигр', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1279, 'Треска', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1280, 'Зимородок', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1281, 'Свинья', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1282, 'Навозный жук', 83);
INSERT INTO animal (id_character, type, wisdom) VALUES (1283, 'список', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1284, 'Морская улитка', 75);
INSERT INTO animal (id_character, type, wisdom) VALUES (1285, 'Летать', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1286, 'Чайка', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1287, 'Свинья', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1288, 'Гремучая змея', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1289, 'Петух', 50);
INSERT INTO animal (id_character, type, wisdom) VALUES (1290, 'Опоссум', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1291, 'Угорь', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1292, 'Собака', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1293, 'Альпака', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1294, 'Куропатка', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1295, 'Палтус', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1296, 'Импала', 35);
INSERT INTO animal (id_character, type, wisdom) VALUES (1297, 'Гриф', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1298, 'Постельный клоп', 19);
INSERT INTO animal (id_character, type, wisdom) VALUES (1299, 'Олень', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1300, 'Птица', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1301, 'Газель', 73);
INSERT INTO animal (id_character, type, wisdom) VALUES (1302, 'Акула-молот', 53);
INSERT INTO animal (id_character, type, wisdom) VALUES (1303, 'Медуза', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1304, 'Осетр', 36);
INSERT INTO animal (id_character, type, wisdom) VALUES (1305, 'Снежный барс', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1306, 'Кашалот', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1307, 'Тукан', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1308, 'Орел', 33);
INSERT INTO animal (id_character, type, wisdom) VALUES (1309, 'Моллюск', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1310, 'ядозуб монстр', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1311, 'Росомаха', 55);
INSERT INTO animal (id_character, type, wisdom) VALUES (1312, 'Орангутанг', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1313, 'Ворона', 45);
INSERT INTO animal (id_character, type, wisdom) VALUES (1314, 'Палтус', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1315, 'Шелкопряд', 69);
INSERT INTO animal (id_character, type, wisdom) VALUES (1316, 'Синяя птица', 56);
INSERT INTO animal (id_character, type, wisdom) VALUES (1317, 'Медведь гризли', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1318, 'Самодовольно', 54);
INSERT INTO animal (id_character, type, wisdom) VALUES (1319, 'тигровая акула', 0);
INSERT INTO animal (id_character, type, wisdom) VALUES (1320, 'Сокол', 35);
INSERT INTO animal (id_character, type, wisdom) VALUES (1321, 'Сиамские бойцовые рыбы', 38);
INSERT INTO animal (id_character, type, wisdom) VALUES (1322, 'Португальский человек войны', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1323, 'Овца', 16);
INSERT INTO animal (id_character, type, wisdom) VALUES (1324, 'Зяблик', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1325, 'Паук', 38);
INSERT INTO animal (id_character, type, wisdom) VALUES (1326, 'Шимпанзе', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1327, 'Рысь', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1328, 'Песчанка', 10);
INSERT INTO animal (id_character, type, wisdom) VALUES (1329, 'Мартышка', 10);
INSERT INTO animal (id_character, type, wisdom) VALUES (1330, 'Мина', 82);
INSERT INTO animal (id_character, type, wisdom) VALUES (1331, 'Морская улитка', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1332, 'Куропатка', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1333, 'Парусник', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1334, 'Волк', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1335, 'Дятел', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1336, 'Мул', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1337, 'Павлин', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1338, 'Монитор ящерицы', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1339, 'Карибу', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1340, 'Краб-стрела', 0);
INSERT INTO animal (id_character, type, wisdom) VALUES (1341, 'Термит', 27);
INSERT INTO animal (id_character, type, wisdom) VALUES (1342, 'Обезьяна паук', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1343, 'Синица', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1344, 'Барракуда', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1345, 'Кошка', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1346, 'Новосветский перепел', 9);
INSERT INTO animal (id_character, type, wisdom) VALUES (1347, 'Лосось', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1348, 'Павлин', 55);
INSERT INTO animal (id_character, type, wisdom) VALUES (1349, 'Краб', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1350, 'Постельный клоп', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1351, 'список', 93);
INSERT INTO animal (id_character, type, wisdom) VALUES (1352, 'Медуза Ируканджи', 3);
INSERT INTO animal (id_character, type, wisdom) VALUES (1353, 'Голубая сойка', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1354, 'Пчела', 37);
INSERT INTO animal (id_character, type, wisdom) VALUES (1355, 'Лосось', 48);
INSERT INTO animal (id_character, type, wisdom) VALUES (1356, 'Игуана', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1357, 'Гуань', 69);
INSERT INTO animal (id_character, type, wisdom) VALUES (1358, 'Гриф', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1359, 'Дракон', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1360, 'Треска', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1361, 'рыба-меч', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1362, 'Жук', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1363, 'Португальский человек войны', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1364, 'Гребешок', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1365, 'Игуана', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1366, 'Мартышка', 51);
INSERT INTO animal (id_character, type, wisdom) VALUES (1367, 'Хамелеон', 93);
INSERT INTO animal (id_character, type, wisdom) VALUES (1368, 'Кузнечик', 35);
INSERT INTO animal (id_character, type, wisdom) VALUES (1369, 'Ракушка', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1370, 'Бык', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1371, 'Бобр', 63);
INSERT INTO animal (id_character, type, wisdom) VALUES (1372, 'Динго', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1373, 'Пиявка', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1374, 'киви', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1375, 'Росомаха', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1376, 'Уиппет', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1377, 'список', 38);
INSERT INTO animal (id_character, type, wisdom) VALUES (1378, 'Рыба-пила', 52);
INSERT INTO animal (id_character, type, wisdom) VALUES (1379, 'Головоногие моллюски', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1380, 'Синий кит', 73);
INSERT INTO animal (id_character, type, wisdom) VALUES (1381, 'Гигантский кальмар', 81);
INSERT INTO animal (id_character, type, wisdom) VALUES (1382, 'Импала', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1383, 'Кондор', 90);
INSERT INTO animal (id_character, type, wisdom) VALUES (1384, 'Хорек', 90);
INSERT INTO animal (id_character, type, wisdom) VALUES (1385, 'Муравейник', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1386, 'Блоха', 100);
INSERT INTO animal (id_character, type, wisdom) VALUES (1387, 'Паук-люк', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1388, 'Мандрил', 6);
INSERT INTO animal (id_character, type, wisdom) VALUES (1389, 'Ехидна', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1390, 'Мастодонт', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1391, 'Морской слон', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1392, 'Колибри', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1393, 'Голубь', 34);
INSERT INTO animal (id_character, type, wisdom) VALUES (1394, 'киви', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1395, 'Альбатрос', 97);
INSERT INTO animal (id_character, type, wisdom) VALUES (1396, 'Медведь гризли', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1397, 'Примас', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1398, 'Буйвол', 90);
INSERT INTO animal (id_character, type, wisdom) VALUES (1399, 'Кит-пилот', 63);
INSERT INTO animal (id_character, type, wisdom) VALUES (1400, 'Цапля', 82);
INSERT INTO animal (id_character, type, wisdom) VALUES (1401, 'Пиранья', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1402, 'Цапля', 100);
INSERT INTO animal (id_character, type, wisdom) VALUES (1403, 'Кошачья акула', 35);
INSERT INTO animal (id_character, type, wisdom) VALUES (1404, 'Гиена', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1405, 'Кенгуру мышь', 33);
INSERT INTO animal (id_character, type, wisdom) VALUES (1406, 'Слон', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1407, 'Обезьяна паук', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1408, 'Змея', 7);
INSERT INTO animal (id_character, type, wisdom) VALUES (1409, 'Дракон', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1410, 'Стрекоза', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1411, 'Криль', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1412, 'Лама', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1413, 'Тунец', 6);
INSERT INTO animal (id_character, type, wisdom) VALUES (1414, 'Бекас', 53);
INSERT INTO animal (id_character, type, wisdom) VALUES (1415, 'Буйвол', 90);
INSERT INTO animal (id_character, type, wisdom) VALUES (1416, 'Рыба-клоун', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1417, 'Сороконожка', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1418, 'Ламантин', 22);
INSERT INTO animal (id_character, type, wisdom) VALUES (1419, 'Осел', 90);
INSERT INTO animal (id_character, type, wisdom) VALUES (1420, 'Дракон Комодо', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1421, 'Крот-звездочка', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1422, 'Крокодил', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1423, 'Ласточка', 77);
INSERT INTO animal (id_character, type, wisdom) VALUES (1424, 'Планарий', 22);
INSERT INTO animal (id_character, type, wisdom) VALUES (1425, 'Пескарь', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1426, 'Аист', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1427, 'Рак-Отшельник', 47);
INSERT INTO animal (id_character, type, wisdom) VALUES (1428, 'Водяной удав', 75);
INSERT INTO animal (id_character, type, wisdom) VALUES (1429, 'Пантера гибрид', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1430, 'Зимородок', 47);
INSERT INTO animal (id_character, type, wisdom) VALUES (1431, 'Лама', 45);
INSERT INTO animal (id_character, type, wisdom) VALUES (1432, 'Нерка', 77);
INSERT INTO animal (id_character, type, wisdom) VALUES (1433, 'Ворона', 41);
INSERT INTO animal (id_character, type, wisdom) VALUES (1434, 'Альпака', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1435, 'Креветки', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1436, 'Утка', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1437, 'Желтый окунь', 16);
INSERT INTO animal (id_character, type, wisdom) VALUES (1438, 'Коала', 35);
INSERT INTO animal (id_character, type, wisdom) VALUES (1439, 'Комар', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1440, 'Эму', 2);
INSERT INTO animal (id_character, type, wisdom) VALUES (1441, 'Сурок', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1442, 'Пантера гибрид', 81);
INSERT INTO animal (id_character, type, wisdom) VALUES (1443, 'Клещ', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1444, 'морская свинка', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1445, 'нести', 9);
INSERT INTO animal (id_character, type, wisdom) VALUES (1446, 'Перепела', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1447, 'Геккон', 33);
INSERT INTO animal (id_character, type, wisdom) VALUES (1448, 'Тар', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1449, 'Тунец', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1450, 'голубь', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1451, 'Альбатрос', 58);
INSERT INTO animal (id_character, type, wisdom) VALUES (1452, 'Орел', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1453, 'Подошва', 81);
INSERT INTO animal (id_character, type, wisdom) VALUES (1454, 'Зяблик', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1455, 'Джей', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1456, 'Собака', 19);
INSERT INTO animal (id_character, type, wisdom) VALUES (1457, 'Галлиформный', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1458, 'Гуанако', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1459, 'Лама', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1460, 'Серебряная рыбка', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1461, 'Синица', 46);
INSERT INTO animal (id_character, type, wisdom) VALUES (1462, 'Кролик', 93);
INSERT INTO animal (id_character, type, wisdom) VALUES (1463, 'Кошачья акула', 3);
INSERT INTO animal (id_character, type, wisdom) VALUES (1464, 'Мина', 46);
INSERT INTO animal (id_character, type, wisdom) VALUES (1465, 'Мина', 85);
INSERT INTO animal (id_character, type, wisdom) VALUES (1466, 'Сорока', 87);
INSERT INTO animal (id_character, type, wisdom) VALUES (1467, 'Гадюка', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1468, 'Обезьяна паук', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1469, 'Гуппи', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1470, 'Летучая мышь', 77);
INSERT INTO animal (id_character, type, wisdom) VALUES (1471, 'Тиранозавр', 45);
INSERT INTO animal (id_character, type, wisdom) VALUES (1472, 'Крыса', 53);
INSERT INTO animal (id_character, type, wisdom) VALUES (1473, 'Барсук', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1474, 'Як', 61);
INSERT INTO animal (id_character, type, wisdom) VALUES (1475, 'Опоссум', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1476, 'Саламандра', 63);
INSERT INTO animal (id_character, type, wisdom) VALUES (1477, 'Лемминг', 22);
INSERT INTO animal (id_character, type, wisdom) VALUES (1478, 'Мартышка', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1479, 'Хамелеон', 6);
INSERT INTO animal (id_character, type, wisdom) VALUES (1480, 'Дракон Комодо', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1481, 'Рак', 27);
INSERT INTO animal (id_character, type, wisdom) VALUES (1482, 'Уиппет', 91);
INSERT INTO animal (id_character, type, wisdom) VALUES (1483, 'Божья коровка', 6);
INSERT INTO animal (id_character, type, wisdom) VALUES (1484, 'Аравийский леопард', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1485, 'Удильщик', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1486, 'Ястреб', 52);
INSERT INTO animal (id_character, type, wisdom) VALUES (1487, 'Шелкопряд', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1488, 'Блоха', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1489, 'Лебедь', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1490, 'Рак-Отшельник', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1491, 'Слон', 81);
INSERT INTO animal (id_character, type, wisdom) VALUES (1492, 'Паук', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1493, 'Тиранозавр', 32);
INSERT INTO animal (id_character, type, wisdom) VALUES (1494, 'Креветки', 39);
INSERT INTO animal (id_character, type, wisdom) VALUES (1495, 'Земляной волк', 0);
INSERT INTO animal (id_character, type, wisdom) VALUES (1496, 'Рыба-клоун', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1497, 'Американский журавль', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1498, 'Олень', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1499, 'Roadrunner', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1500, 'Красная панда', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1501, 'Гагара', 72);
INSERT INTO animal (id_character, type, wisdom) VALUES (1502, 'Гагара', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1503, 'Дрозд', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1504, 'Кольчатый голубь', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1505, 'Сапсан', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1506, 'Щука', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1507, 'Пантера гибрид', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1508, 'Свинья', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1509, 'Барсук', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1510, 'Морж', 41);
INSERT INTO animal (id_character, type, wisdom) VALUES (1511, 'Полевка', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1512, 'Сороконожка', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1513, 'список', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1514, 'Чайка', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1515, 'Желтый окунь', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1516, 'Ягуар', 23);
INSERT INTO animal (id_character, type, wisdom) VALUES (1517, 'Гиббон', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1518, 'Мартышка', 77);
INSERT INTO animal (id_character, type, wisdom) VALUES (1519, 'Барракуда', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1520, 'Кошка', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1521, 'Мартышка', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1522, 'Койот', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1523, 'Лев', 9);
INSERT INTO animal (id_character, type, wisdom) VALUES (1524, 'Сиг', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1525, 'Норка', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1526, 'Скат манта', 58);
INSERT INTO animal (id_character, type, wisdom) VALUES (1527, 'Лошадь', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1528, 'Панда', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1529, 'Дельфин', 9);
INSERT INTO animal (id_character, type, wisdom) VALUES (1530, 'Кенгуру', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1531, 'Утконос', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1532, 'Овцебык', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1533, 'Головоногие моллюски', 7);
INSERT INTO animal (id_character, type, wisdom) VALUES (1534, 'Олень', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1535, 'Лень', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1536, 'Карп', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1537, 'Буффало', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1538, 'Пантера гибрид', 15);
INSERT INTO animal (id_character, type, wisdom) VALUES (1539, 'Скунс', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1540, 'Гусеница', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1541, 'морская свинка', 86);
INSERT INTO animal (id_character, type, wisdom) VALUES (1542, 'Геккон', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1543, 'Росомаха', 69);
INSERT INTO animal (id_character, type, wisdom) VALUES (1544, 'Паук-люк', 50);
INSERT INTO animal (id_character, type, wisdom) VALUES (1545, 'Перепел Старого Света', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1546, 'Пиранья', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1547, 'Скунс', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1548, 'Тар', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1549, 'Коралловый', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1550, 'Фруктовая летучая мышь', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1551, 'Мина', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1552, 'Осел', 70);
INSERT INTO animal (id_character, type, wisdom) VALUES (1553, 'Ласточка', 52);
INSERT INTO animal (id_character, type, wisdom) VALUES (1554, 'Гуппи', 85);
INSERT INTO animal (id_character, type, wisdom) VALUES (1555, 'Змея', 15);
INSERT INTO animal (id_character, type, wisdom) VALUES (1556, 'Панда', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1557, 'Норка', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1558, 'Палтус', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1559, 'Улитка', 3);
INSERT INTO animal (id_character, type, wisdom) VALUES (1560, 'Кенгуру', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1561, 'Ящерица', 7);
INSERT INTO animal (id_character, type, wisdom) VALUES (1562, 'Рыба-клоун', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1563, 'Кузнечик', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1564, 'Орел', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1565, 'Двоякодок', 15);
INSERT INTO animal (id_character, type, wisdom) VALUES (1566, 'Певчая птица', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1567, 'Хорек', 91);
INSERT INTO animal (id_character, type, wisdom) VALUES (1568, 'Балийский скот', 52);
INSERT INTO animal (id_character, type, wisdom) VALUES (1569, 'Птица', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1570, 'Осел', 61);
INSERT INTO animal (id_character, type, wisdom) VALUES (1571, 'Коробка мармеладок', 45);
INSERT INTO animal (id_character, type, wisdom) VALUES (1572, 'Пиранья', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1573, 'Португальский человек войны', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1574, 'Зяблик', 69);
INSERT INTO animal (id_character, type, wisdom) VALUES (1575, 'голубь', 64);
INSERT INTO animal (id_character, type, wisdom) VALUES (1576, 'Лошадь', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1577, 'Двоякодок', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1578, 'Гуппи', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1579, 'Мул', 87);
INSERT INTO animal (id_character, type, wisdom) VALUES (1580, 'Медуза Ируканджи', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1581, 'Дельфин', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1582, 'Жирафа', 35);
INSERT INTO animal (id_character, type, wisdom) VALUES (1583, 'Сцинк', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1584, 'Треска', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1585, 'Валлаби', 51);
INSERT INTO animal (id_character, type, wisdom) VALUES (1586, 'Балийский скот', 9);
INSERT INTO animal (id_character, type, wisdom) VALUES (1587, 'Канюк', 100);
INSERT INTO animal (id_character, type, wisdom) VALUES (1588, 'Хамелеон', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1589, 'Светлячок', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1590, 'нести', 47);
INSERT INTO animal (id_character, type, wisdom) VALUES (1591, 'горный козел', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1592, 'Ястреб', 39);
INSERT INTO animal (id_character, type, wisdom) VALUES (1593, 'Кардинал', 33);
INSERT INTO animal (id_character, type, wisdom) VALUES (1594, 'Кольчатый голубь', 48);
INSERT INTO animal (id_character, type, wisdom) VALUES (1595, 'Минога', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1596, 'Кенгуру', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1597, 'Снежный барс', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1598, 'Журчалка', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1599, 'Буйвол', 87);
INSERT INTO animal (id_character, type, wisdom) VALUES (1600, 'Орел', 89);
INSERT INTO animal (id_character, type, wisdom) VALUES (1601, 'Джунглевая птица', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1602, 'Бизон', 69);
INSERT INTO animal (id_character, type, wisdom) VALUES (1603, 'морская свинка', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1604, 'Пантера', 3);
INSERT INTO animal (id_character, type, wisdom) VALUES (1605, 'Игуана', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1606, 'Гиббон', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1607, 'Сокол', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1608, 'Гадюка', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1609, 'Сапсан', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1610, 'Португальский человек войны', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1611, 'Гигантский кальмар', 91);
INSERT INTO animal (id_character, type, wisdom) VALUES (1612, 'Кролик', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1613, 'Серебряная рыбка', 54);
INSERT INTO animal (id_character, type, wisdom) VALUES (1614, 'Фазан', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1615, 'Дикая кошка', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1616, 'Пескарь', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1617, 'Бовид', 75);
INSERT INTO animal (id_character, type, wisdom) VALUES (1618, 'Соня', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1619, 'ядозуб монстр', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1620, 'Крыса', 50);
INSERT INTO animal (id_character, type, wisdom) VALUES (1621, 'Наземная улитка', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1622, 'Овцебык', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1623, 'Белоголовый орлан', 15);
INSERT INTO animal (id_character, type, wisdom) VALUES (1624, 'Мангуста', 51);
INSERT INTO animal (id_character, type, wisdom) VALUES (1625, 'Пума', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1626, 'Гигантская панда', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1627, 'Импала', 56);
INSERT INTO animal (id_character, type, wisdom) VALUES (1628, 'Подошва', 9);
INSERT INTO animal (id_character, type, wisdom) VALUES (1629, 'Стрекоза', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1630, 'Скорпион', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1631, 'Кашалот', 86);
INSERT INTO animal (id_character, type, wisdom) VALUES (1632, 'Медоуларк', 90);
INSERT INTO animal (id_character, type, wisdom) VALUES (1633, 'Опоссум', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1634, 'Фазан', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1635, 'Корюшка', 27);
INSERT INTO animal (id_character, type, wisdom) VALUES (1636, 'Сурок', 10);
INSERT INTO animal (id_character, type, wisdom) VALUES (1637, 'Серебряная рыбка', 48);
INSERT INTO animal (id_character, type, wisdom) VALUES (1638, 'Постельный клоп', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1639, 'Свинья', 54);
INSERT INTO animal (id_character, type, wisdom) VALUES (1640, 'Крупный рогатый скот', 10);
INSERT INTO animal (id_character, type, wisdom) VALUES (1641, 'Рыба', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1642, 'Як', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1643, 'Лама', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1644, 'Рыба', 15);
INSERT INTO animal (id_character, type, wisdom) VALUES (1645, 'Пескарь', 39);
INSERT INTO animal (id_character, type, wisdom) VALUES (1646, 'Крокодил', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1647, 'Снежный барс', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1648, 'Удав', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1649, 'Летучая рыба', 87);
INSERT INTO animal (id_character, type, wisdom) VALUES (1650, 'Пчела', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1651, 'Моллюск', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1652, 'Желтый окунь', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1653, 'Обезьяна паук', 10);
INSERT INTO animal (id_character, type, wisdom) VALUES (1654, 'Летать', 46);
INSERT INTO animal (id_character, type, wisdom) VALUES (1655, 'Форель', 48);
INSERT INTO animal (id_character, type, wisdom) VALUES (1656, 'Паук', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1657, 'Хорек', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1658, 'Дичь', 50);
INSERT INTO animal (id_character, type, wisdom) VALUES (1659, 'Антилопа', 50);
INSERT INTO animal (id_character, type, wisdom) VALUES (1660, 'Рыба', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1661, 'Куница', 85);
INSERT INTO animal (id_character, type, wisdom) VALUES (1662, 'Бас', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1663, 'Морская свинья', 54);
INSERT INTO animal (id_character, type, wisdom) VALUES (1664, 'Сурикат', 81);
INSERT INTO animal (id_character, type, wisdom) VALUES (1665, 'Хорек', 60);
INSERT INTO animal (id_character, type, wisdom) VALUES (1666, 'Золотая рыбка', 56);
INSERT INTO animal (id_character, type, wisdom) VALUES (1667, 'Паук-люк', 0);
INSERT INTO animal (id_character, type, wisdom) VALUES (1668, 'Слон', 73);
INSERT INTO animal (id_character, type, wisdom) VALUES (1669, 'Хорек', 10);
INSERT INTO animal (id_character, type, wisdom) VALUES (1670, 'Бовид', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1671, 'Рыба', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1672, 'Морской слон', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1673, 'морская свинка', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1674, 'Примас', 16);
INSERT INTO animal (id_character, type, wisdom) VALUES (1675, 'Перепел Старого Света', 27);
INSERT INTO animal (id_character, type, wisdom) VALUES (1676, 'Крупный рогатый скот', 90);
INSERT INTO animal (id_character, type, wisdom) VALUES (1677, 'Соня', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1678, 'Аскариды', 100);
INSERT INTO animal (id_character, type, wisdom) VALUES (1679, 'Осетр', 23);
INSERT INTO animal (id_character, type, wisdom) VALUES (1680, 'Коала', 41);
INSERT INTO animal (id_character, type, wisdom) VALUES (1681, 'Морж', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1682, 'Сокол', 15);
INSERT INTO animal (id_character, type, wisdom) VALUES (1683, 'Гагара', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1684, 'Саблезубый кот', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1685, 'Констриктор', 37);
INSERT INTO animal (id_character, type, wisdom) VALUES (1686, 'Сом', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1687, 'Кошка', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1688, 'Зебра зяблик', 84);
INSERT INTO animal (id_character, type, wisdom) VALUES (1689, 'Тарантул', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1690, 'Альпака', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1691, 'Гриф', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1692, 'Лиса', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1693, 'Летучая мышь вампир', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1694, 'Долгопят', 60);
INSERT INTO animal (id_character, type, wisdom) VALUES (1695, 'Форель', 53);
INSERT INTO animal (id_character, type, wisdom) VALUES (1696, 'заяц', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1697, 'Зяблик', 58);
INSERT INTO animal (id_character, type, wisdom) VALUES (1698, 'Млекопитающее', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1699, 'Гепард', 6);
INSERT INTO animal (id_character, type, wisdom) VALUES (1700, 'Куница', 97);
INSERT INTO animal (id_character, type, wisdom) VALUES (1701, 'Земляной волк', 38);
INSERT INTO animal (id_character, type, wisdom) VALUES (1702, 'Орангутанг', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1703, 'Кит', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1704, 'Скунс', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1705, 'Примас', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1706, 'Crawdad', 73);
INSERT INTO animal (id_character, type, wisdom) VALUES (1707, 'Тля', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1708, 'Нерка', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1709, 'Тасманский дьявол', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1710, 'Овца', 69);
INSERT INTO animal (id_character, type, wisdom) VALUES (1711, 'Карибу', 46);
INSERT INTO animal (id_character, type, wisdom) VALUES (1712, 'Навозный жук', 84);
INSERT INTO animal (id_character, type, wisdom) VALUES (1713, 'Пума', 50);
INSERT INTO animal (id_character, type, wisdom) VALUES (1714, 'Летучая рыба', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1715, 'Мандрил', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1716, 'Собака', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1717, 'Слон', 75);
INSERT INTO animal (id_character, type, wisdom) VALUES (1718, 'Рыба-клоун', 41);
INSERT INTO animal (id_character, type, wisdom) VALUES (1719, 'Гремучая змея', 22);
INSERT INTO animal (id_character, type, wisdom) VALUES (1720, 'Черепаха', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1721, 'Горилла', 70);
INSERT INTO animal (id_character, type, wisdom) VALUES (1722, 'Акула', 85);
INSERT INTO animal (id_character, type, wisdom) VALUES (1723, 'Попугай', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1724, 'Снежный барс', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1725, 'Корюшка', 45);
INSERT INTO animal (id_character, type, wisdom) VALUES (1726, 'Курица', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1727, 'Лебедь', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1728, 'Пингвин', 11);
INSERT INTO animal (id_character, type, wisdom) VALUES (1729, 'Голубь', 9);
INSERT INTO animal (id_character, type, wisdom) VALUES (1730, 'Лимпет', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1731, 'Сова', 58);
INSERT INTO animal (id_character, type, wisdom) VALUES (1732, 'Рыба-пила', 23);
INSERT INTO animal (id_character, type, wisdom) VALUES (1733, 'Гуппи', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1734, 'Буйвол', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1735, 'Олень', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1736, 'Тигр', 87);
INSERT INTO animal (id_character, type, wisdom) VALUES (1737, 'Щука', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1738, 'Кошка', 6);
INSERT INTO animal (id_character, type, wisdom) VALUES (1739, 'нести', 86);
INSERT INTO animal (id_character, type, wisdom) VALUES (1740, 'Лошадь', 57);
INSERT INTO animal (id_character, type, wisdom) VALUES (1741, 'Комар', 19);
INSERT INTO animal (id_character, type, wisdom) VALUES (1742, 'Креветки', 38);
INSERT INTO animal (id_character, type, wisdom) VALUES (1743, 'Анкилостомы', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1744, 'Шакал', 18);
INSERT INTO animal (id_character, type, wisdom) VALUES (1745, 'Аравийский леопард', 75);
INSERT INTO animal (id_character, type, wisdom) VALUES (1746, 'список', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1747, 'Монитор ящерицы', 64);
INSERT INTO animal (id_character, type, wisdom) VALUES (1748, 'Собака', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1749, 'Такин', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1750, 'Сокол', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1751, 'Форель', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1752, 'Синий кит', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1753, 'Сом', 100);
INSERT INTO animal (id_character, type, wisdom) VALUES (1754, 'Рыба-ангел', 23);
INSERT INTO animal (id_character, type, wisdom) VALUES (1755, 'Леопард', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1756, 'Осел', 19);
INSERT INTO animal (id_character, type, wisdom) VALUES (1757, 'Гриф', 35);
INSERT INTO animal (id_character, type, wisdom) VALUES (1758, 'Постельный клоп', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1759, 'Опоссум', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1760, 'Панда', 90);
INSERT INTO animal (id_character, type, wisdom) VALUES (1761, 'Червь', 2);
INSERT INTO animal (id_character, type, wisdom) VALUES (1762, 'Сова', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1763, 'Лосось', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1764, 'Жук', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1765, 'Бабочка', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1766, 'Дельфин', 58);
INSERT INTO animal (id_character, type, wisdom) VALUES (1767, 'список', 9);
INSERT INTO animal (id_character, type, wisdom) VALUES (1768, 'Кролик', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1769, 'Леопон', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1770, 'Синий кит', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1771, 'Ягуар', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1772, 'морская свинка', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1773, 'Термит', 76);
INSERT INTO animal (id_character, type, wisdom) VALUES (1774, 'Наземная акула', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1775, 'Монитор ящерицы', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1776, 'Гагара', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1777, 'Панда', 87);
INSERT INTO animal (id_character, type, wisdom) VALUES (1778, 'Орел', 93);
INSERT INTO animal (id_character, type, wisdom) VALUES (1779, 'Белоголовый орлан', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1780, 'Червь', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1781, 'Щука', 52);
INSERT INTO animal (id_character, type, wisdom) VALUES (1782, 'Перепела', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1783, 'Комар', 11);
INSERT INTO animal (id_character, type, wisdom) VALUES (1784, 'Рак-Отшельник', 9);
INSERT INTO animal (id_character, type, wisdom) VALUES (1785, 'Гиена', 47);
INSERT INTO animal (id_character, type, wisdom) VALUES (1786, 'Crawdad', 7);
INSERT INTO animal (id_character, type, wisdom) VALUES (1787, 'Гепард', 36);
INSERT INTO animal (id_character, type, wisdom) VALUES (1788, 'Лошадь', 54);
INSERT INTO animal (id_character, type, wisdom) VALUES (1789, 'Земляной ленивец', 33);
INSERT INTO animal (id_character, type, wisdom) VALUES (1790, 'Попугай', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1791, 'Журчалка', 36);
INSERT INTO animal (id_character, type, wisdom) VALUES (1792, 'Ара', 41);
INSERT INTO animal (id_character, type, wisdom) VALUES (1793, 'Мул', 39);
INSERT INTO animal (id_character, type, wisdom) VALUES (1794, 'Гуань', 45);
INSERT INTO animal (id_character, type, wisdom) VALUES (1795, 'Олень', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1796, 'Оцелот', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1797, 'Crawdad', 70);
INSERT INTO animal (id_character, type, wisdom) VALUES (1798, 'Куропатка', 10);
INSERT INTO animal (id_character, type, wisdom) VALUES (1799, 'Шелкопряд', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1800, 'Моль', 33);
INSERT INTO animal (id_character, type, wisdom) VALUES (1801, 'Динго', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1802, 'ядозуб монстр', 11);
INSERT INTO animal (id_character, type, wisdom) VALUES (1803, 'Бобр', 51);
INSERT INTO animal (id_character, type, wisdom) VALUES (1804, 'заяц', 64);
INSERT INTO animal (id_character, type, wisdom) VALUES (1805, 'Арктическая лиса', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1806, 'Португальский человек войны', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1807, 'Игуана', 70);
INSERT INTO animal (id_character, type, wisdom) VALUES (1808, 'Гуань', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1809, 'Краб-стрела', 7);
INSERT INTO animal (id_character, type, wisdom) VALUES (1810, 'Ехидна', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1811, 'Леопон', 34);
INSERT INTO animal (id_character, type, wisdom) VALUES (1812, 'Коробка мармеладок', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1813, 'Рысь', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1814, 'Овцебык', 86);
INSERT INTO animal (id_character, type, wisdom) VALUES (1815, 'Дракон', 35);
INSERT INTO animal (id_character, type, wisdom) VALUES (1816, 'Корюшка', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1817, 'Синий кит', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1818, 'Аскариды', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1819, 'Медуза', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1820, 'Импала', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1821, 'Буйвол', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1822, 'Як', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1823, 'Примас', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1824, 'Стальная форель', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1825, 'Карп', 75);
INSERT INTO animal (id_character, type, wisdom) VALUES (1826, 'Курица', 100);
INSERT INTO animal (id_character, type, wisdom) VALUES (1827, 'Дельфин', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1828, 'Примас', 60);
INSERT INTO animal (id_character, type, wisdom) VALUES (1829, 'Павлин', 15);
INSERT INTO animal (id_character, type, wisdom) VALUES (1830, 'Ехидна', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1831, 'Омар', 30);
INSERT INTO animal (id_character, type, wisdom) VALUES (1832, 'Буйвол', 77);
INSERT INTO animal (id_character, type, wisdom) VALUES (1833, 'Кит-пилот', 100);
INSERT INTO animal (id_character, type, wisdom) VALUES (1834, 'Лемур', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1835, 'Карп', 63);
INSERT INTO animal (id_character, type, wisdom) VALUES (1836, 'Попугай', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1837, 'Барсук', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1838, 'Певчая птица', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1839, 'Шершень', 22);
INSERT INTO animal (id_character, type, wisdom) VALUES (1840, 'Орангутанг', 59);
INSERT INTO animal (id_character, type, wisdom) VALUES (1841, 'Сороконожка', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1842, 'Осел', 15);
INSERT INTO animal (id_character, type, wisdom) VALUES (1843, 'Белоголовый орлан', 12);
INSERT INTO animal (id_character, type, wisdom) VALUES (1844, 'Краб-стрела', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1845, 'Эму', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1846, 'Кои', 87);
INSERT INTO animal (id_character, type, wisdom) VALUES (1847, 'Сурикат', 50);
INSERT INTO animal (id_character, type, wisdom) VALUES (1848, 'Креветка', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1849, 'Паук черная вдова', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1850, 'Тарантул', 50);
INSERT INTO animal (id_character, type, wisdom) VALUES (1851, 'Гусь', 23);
INSERT INTO animal (id_character, type, wisdom) VALUES (1852, 'Гремучая змея', 53);
INSERT INTO animal (id_character, type, wisdom) VALUES (1853, 'Сумчатый', 100);
INSERT INTO animal (id_character, type, wisdom) VALUES (1854, 'Антилоп гну', 55);
INSERT INTO animal (id_character, type, wisdom) VALUES (1855, 'Угорь', 75);
INSERT INTO animal (id_character, type, wisdom) VALUES (1856, 'Морской конек', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1857, 'Обезьяна паук', 45);
INSERT INTO animal (id_character, type, wisdom) VALUES (1858, 'Хорек', 32);
INSERT INTO animal (id_character, type, wisdom) VALUES (1859, 'Обезьяна', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1860, 'Орел', 7);
INSERT INTO animal (id_character, type, wisdom) VALUES (1861, 'Английский указатель', 34);
INSERT INTO animal (id_character, type, wisdom) VALUES (1862, 'Кит', 100);
INSERT INTO animal (id_character, type, wisdom) VALUES (1863, 'Пантера', 77);
INSERT INTO animal (id_character, type, wisdom) VALUES (1864, 'Рыба-попугай', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1865, 'Соловей', 6);
INSERT INTO animal (id_character, type, wisdom) VALUES (1866, 'Скумбрия', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1867, 'Синий кит', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1868, 'Пересмешник', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1869, 'Криль', 81);
INSERT INTO animal (id_character, type, wisdom) VALUES (1870, 'Обезьяна паук', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1871, 'Койот', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1872, 'Пума', 85);
INSERT INTO animal (id_character, type, wisdom) VALUES (1873, 'Осьминог', 82);
INSERT INTO animal (id_character, type, wisdom) VALUES (1874, 'список', 55);
INSERT INTO animal (id_character, type, wisdom) VALUES (1875, 'Барсук', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1876, 'Лень', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1877, 'Сумчатый', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1878, 'Кенгуровая крыса', 82);
INSERT INTO animal (id_character, type, wisdom) VALUES (1879, 'Козел', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1880, 'Светлячок', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1881, 'Обезьяна', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1882, 'Шершень', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1883, 'Колпица', 66);
INSERT INTO animal (id_character, type, wisdom) VALUES (1884, 'Полярный медведь', 53);
INSERT INTO animal (id_character, type, wisdom) VALUES (1885, 'Кольчатый голубь', 44);
INSERT INTO animal (id_character, type, wisdom) VALUES (1886, 'Павлин', 13);
INSERT INTO animal (id_character, type, wisdom) VALUES (1887, 'Слон', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1888, 'Пума', 97);
INSERT INTO animal (id_character, type, wisdom) VALUES (1889, 'Грызун', 61);
INSERT INTO animal (id_character, type, wisdom) VALUES (1890, 'Такин', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1891, 'Светлячок', 74);
INSERT INTO animal (id_character, type, wisdom) VALUES (1892, 'Светлячок', 64);
INSERT INTO animal (id_character, type, wisdom) VALUES (1893, 'рыба-меч', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1894, 'Аравийский леопард', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1895, 'Джей', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1896, 'Валлаби', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1897, 'Бобр', 62);
INSERT INTO animal (id_character, type, wisdom) VALUES (1898, 'Клювый кит', 63);
INSERT INTO animal (id_character, type, wisdom) VALUES (1899, 'Лиса', 4);
INSERT INTO animal (id_character, type, wisdom) VALUES (1900, 'Такин', 49);
INSERT INTO animal (id_character, type, wisdom) VALUES (1901, 'Рак-Отшельник', 33);
INSERT INTO animal (id_character, type, wisdom) VALUES (1902, 'Гусь', 0);
INSERT INTO animal (id_character, type, wisdom) VALUES (1903, 'Тунец', 28);
INSERT INTO animal (id_character, type, wisdom) VALUES (1904, 'Радужная форель', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1905, 'Лемур', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1906, 'Сиамские бойцовые рыбы', 93);
INSERT INTO animal (id_character, type, wisdom) VALUES (1907, 'список', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1908, 'Соловей', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1909, 'Цапля', 68);
INSERT INTO animal (id_character, type, wisdom) VALUES (1910, 'Олень', 22);
INSERT INTO animal (id_character, type, wisdom) VALUES (1911, 'Паук', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1912, 'Медведь гризли', 97);
INSERT INTO animal (id_character, type, wisdom) VALUES (1913, 'Гиена', 17);
INSERT INTO animal (id_character, type, wisdom) VALUES (1914, 'Цапля', 65);
INSERT INTO animal (id_character, type, wisdom) VALUES (1915, 'Росомаха', 97);
INSERT INTO animal (id_character, type, wisdom) VALUES (1916, 'Тапир', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1917, 'Попугай', 54);
INSERT INTO animal (id_character, type, wisdom) VALUES (1918, 'Кит', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1919, 'Осел', 16);
INSERT INTO animal (id_character, type, wisdom) VALUES (1920, 'Пчела', 10);
INSERT INTO animal (id_character, type, wisdom) VALUES (1921, 'Кабан', 83);
INSERT INTO animal (id_character, type, wisdom) VALUES (1922, 'Кашалот', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1923, 'Минога', 64);
INSERT INTO animal (id_character, type, wisdom) VALUES (1924, 'Колибри', 55);
INSERT INTO animal (id_character, type, wisdom) VALUES (1925, 'Хорек', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1926, 'Навозный жук', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1927, 'Чайка', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1928, 'Морская улитка', 6);
INSERT INTO animal (id_character, type, wisdom) VALUES (1929, 'Гиена', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1930, 'Полевка', 42);
INSERT INTO animal (id_character, type, wisdom) VALUES (1931, 'Выдра', 94);
INSERT INTO animal (id_character, type, wisdom) VALUES (1932, 'Шершень', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1933, 'лось', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1934, 'Бекас', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1935, 'Колибри', 23);
INSERT INTO animal (id_character, type, wisdom) VALUES (1936, 'Crawdad', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1937, 'Crawdad', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1938, 'Крапивник', 26);
INSERT INTO animal (id_character, type, wisdom) VALUES (1939, 'Кенгуру', 18);
INSERT INTO animal (id_character, type, wisdom) VALUES (1940, 'Опоссум', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1941, 'Акула-молот', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1942, 'Тупик', 34);
INSERT INTO animal (id_character, type, wisdom) VALUES (1943, 'Земляной волк', 21);
INSERT INTO animal (id_character, type, wisdom) VALUES (1944, 'Дельфин', 11);
INSERT INTO animal (id_character, type, wisdom) VALUES (1945, 'Обезьяна', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1946, 'Таракан', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1947, 'Марлин', 25);
INSERT INTO animal (id_character, type, wisdom) VALUES (1948, 'Рысь', 34);
INSERT INTO animal (id_character, type, wisdom) VALUES (1949, 'Crawdad', 39);
INSERT INTO animal (id_character, type, wisdom) VALUES (1950, 'Курица', 37);
INSERT INTO animal (id_character, type, wisdom) VALUES (1951, 'морская свинка', 69);
INSERT INTO animal (id_character, type, wisdom) VALUES (1952, 'Светлячок', 95);
INSERT INTO animal (id_character, type, wisdom) VALUES (1953, 'Мандрил', 98);
INSERT INTO animal (id_character, type, wisdom) VALUES (1954, 'Голубь', 69);
INSERT INTO animal (id_character, type, wisdom) VALUES (1955, 'Альбатрос', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1956, 'тигровая акула', 24);
INSERT INTO animal (id_character, type, wisdom) VALUES (1957, 'Окунь', 14);
INSERT INTO animal (id_character, type, wisdom) VALUES (1958, 'Лошадь', 78);
INSERT INTO animal (id_character, type, wisdom) VALUES (1959, 'Крыса', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1960, 'Тукан', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1961, 'Сурок', 23);
INSERT INTO animal (id_character, type, wisdom) VALUES (1962, 'Хорек', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1963, 'Балийский скот', 69);
INSERT INTO animal (id_character, type, wisdom) VALUES (1964, 'Свинья', 37);
INSERT INTO animal (id_character, type, wisdom) VALUES (1965, 'Фазан', 84);
INSERT INTO animal (id_character, type, wisdom) VALUES (1966, 'Шершень', 99);
INSERT INTO animal (id_character, type, wisdom) VALUES (1967, 'Пчела', 29);
INSERT INTO animal (id_character, type, wisdom) VALUES (1968, 'Сапсан', 19);
INSERT INTO animal (id_character, type, wisdom) VALUES (1969, 'Морская улитка', 67);
INSERT INTO animal (id_character, type, wisdom) VALUES (1970, 'Буйвол', 52);
INSERT INTO animal (id_character, type, wisdom) VALUES (1971, 'Дичь', 72);
INSERT INTO animal (id_character, type, wisdom) VALUES (1972, 'Ламантин', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1973, 'Краб', 63);
INSERT INTO animal (id_character, type, wisdom) VALUES (1974, 'Новосветский перепел', 91);
INSERT INTO animal (id_character, type, wisdom) VALUES (1975, 'Летучая мышь', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1976, 'Парусник', 88);
INSERT INTO animal (id_character, type, wisdom) VALUES (1977, 'Фазан', 18);
INSERT INTO animal (id_character, type, wisdom) VALUES (1978, 'Олень', 8);
INSERT INTO animal (id_character, type, wisdom) VALUES (1979, 'Корова', 43);
INSERT INTO animal (id_character, type, wisdom) VALUES (1980, 'Сапсан', 75);
INSERT INTO animal (id_character, type, wisdom) VALUES (1981, 'Двоякодок', 1);
INSERT INTO animal (id_character, type, wisdom) VALUES (1982, 'Норка', 37);
INSERT INTO animal (id_character, type, wisdom) VALUES (1983, 'Цапля', 48);
INSERT INTO animal (id_character, type, wisdom) VALUES (1984, 'Голубь', 5);
INSERT INTO animal (id_character, type, wisdom) VALUES (1985, 'Хомяк', 20);
INSERT INTO animal (id_character, type, wisdom) VALUES (1986, 'лось', 70);
INSERT INTO animal (id_character, type, wisdom) VALUES (1987, 'Краб-стрела', 48);
INSERT INTO animal (id_character, type, wisdom) VALUES (1988, 'Рыба-пила', 86);
INSERT INTO animal (id_character, type, wisdom) VALUES (1989, 'Попугай', 31);
INSERT INTO animal (id_character, type, wisdom) VALUES (1990, 'Уховертка', 71);
INSERT INTO animal (id_character, type, wisdom) VALUES (1991, 'Скат манта', 97);
INSERT INTO animal (id_character, type, wisdom) VALUES (1992, 'Бас', 79);
INSERT INTO animal (id_character, type, wisdom) VALUES (1993, 'Кенгуру', 64);
INSERT INTO animal (id_character, type, wisdom) VALUES (1994, 'Куница', 80);
INSERT INTO animal (id_character, type, wisdom) VALUES (1995, 'Альбатрос', 92);
INSERT INTO animal (id_character, type, wisdom) VALUES (1996, 'Лунь', 40);
INSERT INTO animal (id_character, type, wisdom) VALUES (1997, 'Рыба-пила', 52);
INSERT INTO animal (id_character, type, wisdom) VALUES (1998, 'Чешуйчатое насекомое', 96);
INSERT INTO animal (id_character, type, wisdom) VALUES (1999, 'Утка', 47);
